version: '3'

services:
  currencies-airflow:
    image: apache/airflow:latest
    volumes:
      - ./airflow:/opt/airflow
      - ./airflow/data:/app/data
    ports:
      - "8080:8080"
    command: airflow standalone